
BLENDER="C:\Program Files\Blender Foundation\Blender 2.93\blender.exe"
DIST=../dist

all : \
    $(DIST)/mine.pnct \
    $(DIST)/mine.scene \

$(DIST)/mine.scene : mine.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "mine.blend:Collection" "$(DIST)/mine.scene"

$(DIST)/mine.pnct : mine.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "mine.blend:Collection" "$(DIST)/mine.pnct" 
